config/routes.rb
Rails.application.routes.draw do

  resources :movements
  resources :goals
  resources :warranties 
  resources :concepts
  resources :accounts 
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  
  get 'main', to: 'home#dashboard', as: 'dashboard' 
  get 'mi_familia', to: 'familia#mi_familia', as: 'mi_familia' 
  get  'nuevo_familiar' , to: 'familia#nuevo_familiar', as: 'nuevo_familiar'
  post 'registro_familia', to: 'familia#registro_nuevo_familar', as: 'registro_familia'
  post 'add_reference/:id', to: 'warranties#add_reference', as: 'add_reference'
  get 'warranties/:id/image', to: 'warranties#show_image', as: 'show_image'
  delete 'warranties/:id/:warranty', to: 'warranties#destroy_image', as: 'destroy_images_warranty'
end

app/models/movement.rb
# == Schema Information
#
# Table name: movements
#
#  id          :integer          not null, primary key
#  descripcion :string
#  cantidad    :decimal(, )
#  account_id  :integer          not null
#  concept_id  :integer          not null
#  user_id     :integer          not null
#  goal_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Movement < ApplicationRecord
belongs_to :user


  def guardad_movimientos(usuario)
      self.user_id = usuario.id
      concepto = Concept.find(self.concept_id)
      if concepto.tipo == 1
        incrementar_saldo
      elsif concepto.tipo == 2
        decrementar_saldo
      end
      # Guarda el objeto movimiento y retorna el objeto si se guardó correctamente, en caso contrario retorna nil
      if self.save
        self
      else
        nil
      end
  end
  

  def decrementar_saldo
      # Busca la cuenta relacionada con el id de cuenta del objeto movimiento
      cuenta = Account.find(self.account_id)
      # Actualiza el saldo de la cuenta restando la cantidad del movimiento
      cuenta.saldo = cuenta.saldo - self.cantidad.to_f
      # Guarda los cambios en la cuenta
      cuenta.save
    end
  end

    def incrementar_saldo
      cuenta = Account.find(self.account_id)
      cuenta.saldo = cuenta.saldo + self.cantidad.to_f
      cuenta.save
    end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
 

  # GET /movements or /movements.json
  def index
    if current_user.nil?
      redirect_to new_user_session_path and return
    end
    if current_user.tipo_usuario == 1
      @movements = Movement.all
    else
      @movements = current_user.movements
    end
  end

  # GET /movements/1 or /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = Movement.new
    @conceptos = Concept.conceptos_familiares(current_user.family_id) 
    @cuenta = Account.cuentas_personales(current_user.id)
    @goals = Goal.metas_familiares(current_user.family_id)

  end

  # GET /movements/1/edit
  def edit
    @conceptos = Concept.conceptos_familiares(current_user.family_id) 
    @cuenta = Account.cuentas_personales(current_user.id)
    @goals = Goal.metas_familiares(current_user.family_id)
  end

  # POST /movements or /movements.json
  def create
    @movement = Movement.new(movement_params)
    movimiento = @movement.guardad_movimientos(current_user)
    
    respond_to do |format|
      if movimiento
        NotificationMailer.notification_movement(current_user, @movement).deliver_later
        format.html { redirect_to movement_url(@movement), notice: "El movimiento ah sido creado correctamente. " }
        format.json { render :show, status: :created, location: @movement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movements/1 or /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to movement_url(@movement), notice: "El movimiento ah sido modificado correctamente. " }
        format.json { render :show, status: :ok, location: @movement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1 or /movements/1.json
  def destroy
    @movement.destroy

    respond_to do |format|
      format.html { redirect_to movements_url, notice: "El movimiento ah sido eliminado correctamebnte. " }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movement_params
      params.require(:movement).permit(:descripcion, :cantidad, :account_id, :concept_id, :user_id, :goal_id)
    end
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/movements/_form.html.erb
<%= form_with(model: movement, local: true) do |form| %>
  <% if movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
        <% movement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= form.label 'Concepto'%>
      <%= form.collection_select(:concept_id, @conceptos, :id, :nombre, prompt: true) %>
  </div>

  <div class="field">
      <%= form.label 'Cuenta' %>
      <%= form.collection_select(:account_id, @cuenta, :id, :nombre, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.text_field :cantidad %>
  </div>

   <div class="field">
      <%= form.label 'Metas'%>
      <%= form.collection_select(:goal_id, @goals, :id, :nombre, prompt: true) %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movements/edit.html.erb
<h1>Editing Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/index.html.erb
<h1>Mis Movimientos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Cantidad</th>
      <th>Cuenta</th>
      <th>Concepto</th>
      <th>Metas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movements.each do |movement| %>
      <tr>
        <td><%= movement.descripcion %></td>
        <td><%= movement.cantidad %></td>
        <td><%= movement.account_id %></td>
        <td><%= movement.concept_id %></td>
        <td><%= movement.goal_id %></td>
        <td><%= link_to 'Show', movement %></td>
        <td><%= link_to 'Edit', edit_movement_path(movement) %></td>
        <td><%= link_to 'Destroy', movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movement', new_movement_path %>

app/views/movements/new.html.erb
<h1>Nuevo Movimiento</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Back', movements_path %>

app/views/movements/show.html.erb
<p>
  <strong>Descripcion:</strong>
  <%= @movement.descripcion %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @movement.cantidad %>
</p>

<p>
  <strong>Cuenta:</strong>
  <%= @movement.account_id %>
</p>

<p>
  <strong>Concepto:</strong>
  <%= @movement.concept_id %>
</p>


<p>
  <strong>Meta:</strong>
  <%= @movement.goal_id %>
</p>

<%= link_to 'Edit', edit_movement_path(@movement) %> |
<%= link_to 'Back', movements_path %>