config/routes.rb
Rails.application.routes.draw do

  resources :movements
  resources :goals
  resources :warranties 
  resources :concepts
  resources :accounts 
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  
  get 'main', to: 'home#dashboard', as: 'dashboard' 
  get 'mi_familia', to: 'familia#mi_familia', as: 'mi_familia' 
  get  'nuevo_familiar' , to: 'familia#nuevo_familiar', as: 'nuevo_familiar'
  post 'registro_familia', to: 'familia#registro_nuevo_familar', as: 'registro_familia'
  post 'add_reference/:id', to: 'warranties#add_reference', as: 'add_reference'
  get 'warranties/:id/image', to: 'warranties#show_image', as: 'show_image'
  delete 'warranties/:id/:warranty', to: 'warranties#destroy_image', as: 'destroy_images_warranty'
end

app/models/warranty.rb
# == Schema Information
#
# Table name: warranties
#
#  id                :integer          not null, primary key
#  nombre            :string
#  no_identificacion :string
#  fecha_adq         :date
#  estado            :string
#  periodo_dias      :integer
#  dias_restantes    :integer
#  user_id           :integer          not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Warranty < ApplicationRecord
  validates :nombre, :no_identificacion, :estado, :fecha_adq, presence: true
  validates :periodo_dias, presence: true, numericality: { only_integer: true, greater_than: 0 }
  belongs_to :user
  
  # Declarar una relación uno a uno con un archivo adjunto llamado "comprobante_garantia"
  # que se manejará mediante ActiveStorage
  has_many_attached :comprobante_garantia

  def guardar_garantia(usuario)
    # Asigna el id del usuario al objeto garantía
    self.user_id = usuario.id
    # Guarda el objeto garantía y retorna el objeto si se guardó correctamente, en caso contrario retorna nil
    if self.save
      self
    else
      nil
    end
  end

  def dias_restantes
    # Calcula la fecha final de la garantía sumando los días de duración a la fecha de adquisición
    fecha_final = self.fecha_adq + self.periodo_dias
    # Calcula los días restantes restando la fecha actual a la fecha final de la garantía
    self.dias_restantes = (fecha_final - Date.today).to_i
    self.save
  end

  


  
end

app/controllers/warranties_controller.rb
class WarrantiesController < ApplicationController
  before_action :set_warranty, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /warranties or /warranties.json
  def index
    @warranties = Warranty.all
  end

  # GET /warranties/1 or /warranties/1.json
  def show
    
  end

  def show_image
    @warranty = Warranty.find(params[:id])
    if @warranty.comprobante_garantia.attached?
      @comprobante_garantia = @warranty.comprobante_garantia
    else
      redirect_to @warranty, notice: "La garantía no tiene ningún comprobante adjunto."
    end
end

def destroy_image
  @warranty = Warranty.find(params[:warranty])
  @warranty.comprobante_garantia.purge
  redirect_to @warranty, notice: "Comprobante de garantía eliminado correctamente."
end


def add_reference  
  @warranty = Warranty.find(params[:id])
  if params[:warranty][:comprobante_garantia]
    if ["image/jpeg", "image/png", "application/pdf"].include?(params[:warranty][:comprobante_garantia].content_type)
      @warranty.comprobante_garantia.attach(params[:warranty][:comprobante_garantia])
      if @warranty.comprobante_garantia.attached?
        redirect_to @warranty, notice: "Comprobante de garantía subido correctamente."
      else
        redirect_to @warranty, alert: "No se pudo subir el comprobante de garantía."
      end
    else
      redirect_to @warranty, alert: "Solo se permiten archivos de tipo JPEG, PNG y PDF"
    end
  else
    redirect_to @warranty, alert: "No se ha seleccionado ningún archivo para subir."
  end
end





  # GET /warranties/new
  def new
    @warranty = Warranty.new
  end

  # GET /warranties/1/edit
  def edit
  end

  # POST /warranties or /warranties.json
  def create
    @warranty = Warranty.new(warranty_params)
    garantia = @warranty.guardar_garantia(current_user)

    respond_to do |format|
      if garantia
        NotificationMailer.notification_warranty(current_user, @warranty).deliver_later
        format.html { redirect_to warranty_url(@warranty), notice: "La gaantia ah sido creada correctamente." }
        format.json { render :show, status: :created, location: @warranty }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warranty.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # PATCH/PUT /warranties/1 or /warranties/1.json
  def update
    respond_to do |format|
      if @warranty.update(warranty_params)
        format.html { redirect_to warranty_url(@warranty), notice: "La gaantia ah sido modificada correctamente." }
        format.json { render :show, status: :ok, location: @warranty }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @warranty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warranties/1 or /warranties/1.json
  def destroy
    @warranty.destroy

    respond_to do |format|
      format.html { redirect_to warranties_url, notice: "La garantia ah sido eliminada correctamente. " }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warranty
      @warranty = Warranty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def warranty_params
      params.require(:warranty).permit(:nombre, :no_identificacion, :fecha_adq, :estado, :periodo_dias, :dias_restantes, :user_id, :comprobante_garantia)
    end
end

app/helpers/warranties_helper.rb
module WarrantiesHelper
end

app/views/warranties/_form.html.erb
<%= form_with(model: warranty, local: true) do |form| %>
  <% if warranty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warranty.errors.count, "error") %> prohibited this warranty from being saved:</h2>

      <ul>
        <% warranty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :no_identificacion %>
    <%= form.text_field :no_identificacion %>
  </div>

  <div class="field">
    <%= form.label :fecha_adq %>
    <%= form.date_select :fecha_adq %>
  </div>

  <div class="field">
    <%= form.label "Estado" %>
    <span class="radio-inline">
      <%= form.radio_button(:estado, 'Activa') %>
      <%= form.label "Activa" %>
    </span>
    <span class="radio-inline">
      <%= form.radio_button(:estado, 'Vencida') %>
      <%= form.label "Vencida" %>
    </span>
  </div>

  <div class="field">
    <%= form.label :periodo_dias %>
    <%= form.number_field :periodo_dias %>
  </div>

  <div>
  <%= form.label :referencia %>
  <%= form.file_field :referencia %>
  </div>
<br> <br> <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warranties/edit.html.erb
<h1>Editing Warranty</h1>

<%= render 'form', warranty: @warranty %>

<%= link_to 'Show', @warranty %> |
<%= link_to 'Back', warranties_path %>

app/views/warranties/index.html.erb
<h1>Mis Garantias</h1>

<table>
  <thead>
    <table cellpadding="20">
    <tr>
      <th>Nombre</th>
      <th>No identificacion</th>
      <th>Fecha de adquisicion</th>
      <th>Estado</th>
      <th>Periodo dias</th>
      <th>Dias restantes</th>
      <th colspan="3"></th>
    </tr>
    </table>
  </thead>

  <tbody>
    <% @warranties.each do |warranty| %>
    <table cellpadding="10">
      <tr>
        <td><%= warranty.nombre %></td>
        <td><%= warranty.no_identificacion %></td>
        <td><%= warranty.fecha_adq %></td>
        <td><%= warranty.estado %></td>
        <td><%= warranty.periodo_dias %></td>
        <td><%= warranty.dias_restantes %></td>
        <td><%= link_to 'Show', warranty %></td>
        <td><%= link_to 'Edit', edit_warranty_path(warranty) %></td>
        <td><%= link_to 'Destroy', warranty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </table>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Garantia', new_warranty_path %>

app/views/warranties/new.html.erb
<h1>New Warranty</h1>

<%= render 'form', warranty: @warranty %>

<%= link_to 'Back', warranties_path %>

app/views/warranties/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @warranty.nombre %>
</p>

<p>
  <strong>No identificacion:</strong>
  <%= @warranty.no_identificacion %>
</p>

<p>
  <strong>Fecha adq:</strong>
  <%= @warranty.fecha_adq %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @warranty.estado %>
</p>

<p>
  <strong>Periodo dias:</strong>
  <%= @warranty.periodo_dias %>
</p>

<p>
  <strong>Dias restantes:</strong>
  <%= @warranty.dias_restantes %>
</p>

<div>
<%= form_with model: @warranty, url: add_reference_path(@warranty), method: :post, multipart: true do |form| %>
  <!-- Crea un campo oculto para pasar el id de la garantía al controlador -->
  <%= form.hidden_field :id %>
  <!-- Crea un campo de tipo file para subir el archivo de referencia -->
  <%= form.file_field :comprobante_garantia %>
  <!-- Crea un botón para enviar el formulario -->
  <%= form.submit "Agregar referencia" %>
<% end %>
</div>
<br><br>
<div>
  <% if @warranty.comprobante_garantia.attached? %>
    <% @warranty.comprobante_garantia.each do |archivo|%>
        <% if archivo.content_type.include?("image") %>
          <%= image_tag(archivo.variant(resize: '300x300')) %>
        <% elsif archivo.content_type.include?("pdf") %>
          <%= image_tag("pdf_logo.png") %> <%= archivo.filename %>
          <%= link_to archivo, target: "_blank" do %>
               Ver PDF
        <% end %>
        <% end %> 
        <%= link_to "Ver comprobante de garantía original", rails_blob_path(archivo) %>
        <%= link_to "Eliminar comprobante de garantía", destroy_images_warranty_path(archivo.signed_id, @warranty.id), method: :delete %>
    <%end%>
  <% end %>
</div>



<%= link_to 'Edit', edit_warranty_path(@warranty) %> |
<%= link_to 'Back', warranties_path %>