config/routes.rb
Rails.application.routes.draw do

  resources :movements
  resources :goals
  resources :warranties 
  resources :concepts
  resources :accounts 
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  
  get 'main', to: 'home#dashboard', as: 'dashboard' 
  get 'mi_familia', to: 'familia#mi_familia', as: 'mi_familia' 
  get  'nuevo_familiar' , to: 'familia#nuevo_familiar', as: 'nuevo_familiar'
  post 'registro_familia', to: 'familia#registro_nuevo_familar', as: 'registro_familia'
  post 'add_reference/:id', to: 'warranties#add_reference', as: 'add_reference'
  get 'warranties/:id/image', to: 'warranties#show_image', as: 'show_image'
  delete 'warranties/:id/:warranty', to: 'warranties#destroy_image', as: 'destroy_images_warranty'
end

app/models/concept.rb
# == Schema Information
#
# Table name: concepts
#
#  id          :integer          not null, primary key
#  nombre      :string
#  tipo        :integer
#  descripcion :string
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Concept < ApplicationRecord
  validates :nombre, :tipo, :descripcion, presence: true
  #validates :tipo, numericality: { only_integer: true }
  validates :tipo, inclusion: { in: [1, 2] }
  belongs_to :user


  def guardar_concept(usuario)
    # Asigna el id del usuario al objeto concepto
    self.user_id = usuario.id
    # Guarda el objeto concepto y retorna el objeto si se guardó correctamente, en caso contrario retorna nil
    if self.save
      self
    else
      nil
    end
  end

    def self.conceptos_familiares(family_id)
      #consulta para traer todos los usuarios de una familia 
      #select * from users where family_id = [family_id]
      usuarios = User.where(family_id: family_id)
      if usuarios
        #consulta para optener los conceptos de los usuarios optenidos 
        Concept.where(user_id: usuarios)
      else
        nil
      end

    end

end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :set_concept, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /concepts or /concepts.json
  def index
    if current_user.nil?
      redirect_to new_user_session_path and return
    end
    if current_user.tipo_usuario == 1
      @concepts = Concept.all
    else
      @concepts = current_user.concepts
    end
  end
  
  # GET /concepts/1 or /concepts/1.json
  def show
  end

  # GET /concepts/new
  def new
    @concept = Concept.new
  end

  # GET /concepts/1/edit
  def edit
  end

  # POST /concepts or /concepts.json
  def create
    @concept = Concept.new(concept_params)
    concepto = @concept.guardar_concept(current_user)

    respond_to do |format|
      if concepto
        format.html { redirect_to concept_url(@concept), notice: "El concepto ah sido creado correctamente." }
        format.json { render :show, status: :created, location: @concept }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concepts/1 or /concepts/1.json
  def update
    respond_to do |format|
      if @concept.update(concept_params)
        format.html { redirect_to concept_url(@concept), notice: "El concepto ah sido modificado correctamente." }
        format.json { render :show, status: :ok, location: @concept }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1 or /concepts/1.json
  def destroy
    @concept.destroy

    respond_to do |format|
      format.html { redirect_to concepts_url, notice: "El concepto ah sido eliminado correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concept
      @concept = Concept.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concept_params
      params.require(:concept).permit(:nombre, :tipo, :descripcion, :user_id)
    end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/views/concepts/_form.html.erb
<%= form_with(model: concept, local: true) do |form| %>
  <% if concept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

      <ul>
        <% concept.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label "Tipo Concepto" %>
    <span class="radio-inline">
      <%= form.radio_button(:tipo, 1) %>
      <%= form.label "Ingreso" %>
    </span>
    <span class="radio-inline">
      <%= form.radio_button(:tipo, 2) %>
      <%= form.label "Egreso" %>
    </span>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concepts/edit.html.erb
<h1>Editar Concept</h1>

<%= render 'form', concept: @concept %>

<%= link_to 'Show', @concept %> |
<%= link_to 'Atras', concepts_path %>

app/views/concepts/index.html.erb
<h1>Conceptos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td><%= concept.nombre %></td>
        <td><%= concept.tipo %></td>
        <td><%= concept.descripcion %></td>
        <td><%= link_to 'Show', concept %></td>
        <td><%= link_to 'Edit', edit_concept_path(concept) %></td>
        <td><%= link_to 'Destroy', concept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Concepto', new_concept_path %>

app/views/concepts/new.html.erb
<h1>Nuevo Concepto</h1>

<%= render 'form', concept: @concept %>

<%= link_to 'Back', concepts_path %>

app/views/concepts/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @concept.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @concept.tipo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @concept.descripcion %>
</p>


<%= link_to 'Edit', edit_concept_path(@concept) %> |
<%= link_to 'Back', concepts_path %>